### PR TITLE
Feat: Replace app icon and splash screen

### PR DESCRIPTION
**Pull request by marcstfx**
### Description

Replace app icon and splash screen.

---

### Acceptance Criteria

- [x] Splash screen shows thght logomark
- [x] App icon shows thght logomark

---

### CODE REVIEW

**Comment by tderleth** [comment]
@marcstfx please adjust splash screen size 👍

**Review by tderleth — CHANGES_REQUESTED** [review]
@marcstfx I added tests. Please adjust splash screen size 👍

**Comment by tderleth** [comment]
```
FAIL src/tests/assets/spash-screen.test.ts (5.702s)
  ● splash-screen › should check dimensions of splash screen

    expect(received).toEqual(expected) // deep equality

    Expected: 1242
    Received: 1125

       9 |   it('should check dimensions of splash screen', () => {
      10 |     const dimensions = imageSize(path);
    > 11 |     expect(dimensions.width).toEqual(1242);
         |                              ^
      12 |     expect(dimensions.height).toEqual(2436);
      13 |   });
      14 | });

      at Object.<anonymous> (src/tests/assets/spash-screen.test.ts:11:30)
```

**Review by marcstfx — COMMENTED** [review]
.

**Comment by tderleth** [comment]
> .

[ok](https://gph.is/1a7RlDR)

**Comment by tderleth** [comment]
> .

discoveryeurope-discovery-woo-1qWO2hUWKPrHhEbgg7

**Review by tderleth — APPROVED** [review]

**Review by marcstfx — COMMENTED** [review]
Added splash image in correct dimensions

**Review by marcstfx — COMMENTED** [review]
k

**Comment by tderleth** [comment]
> k

japan-jpop-xT1R9Dn3s8Svhw2LMk

**Pull request merged**
